language: node_js
node_js:
- '8'
- '6'
deploy:
  provider: npm
  email: ops@craft.ai
  api_key:
    secure: mdmhtyQmOnCXtRGEZUa+E97rKi97bjwtNfSX43yZofMA3TgENHRQLLWXnu9GlrYSYbmCu4P4g6ss9rpWeqnIkE/7YkhCz1PYNacld6yubLq3cHxfjc0aBz2RBNuA/NZHK6dFagKcLo7Jlrg9GRVrznrfyxjbsojshvBWftQoP549YDFzPBsTqoZkQrfL0d2EFcK/pM5AoBBKCWvpCXY/hSwaQEujpEemKtH8lwXPzEnttSZN7iAod11VXRbL02hCvSA+noGL8f1zVsQM0y9DzScHakoopgWYoHw1+E+9i2iOi7DwsHAB3KbAkE5BccxGWa8DiPSUPeULRZWp0LRw/R9QxKyJvn5Xy0SvvEMMfEXFsw4GCZgkFejH5UwZkhbCHS5yubopXvK8gg6Xl0mVM+Oj99YIS/hRjXYvKxeDutWdCHEv/IdNE7OrSdZXRt69u/afC/IEf5bCR3BdcTsWnDQ2sfCjnF631l3+594TvpMk8hHD0WfIMIlTgC2b72sNYjvmJvMQZ2s+OLYP/o6zVc5WS53ZbBPMgvaGKvIWTh6kS6CdMrnoCmQNXMFq7FwlbB08AiC2Hkr/tbzfdkqX58hralzJ+SsoPB+H6EFnAeJ5u1uV4X2hoR0i8m8TDR0/cRmorbnTwiJr6oLnkPWNPAgpqTbWUIfFwkPdfavNBg8=
  on:
    node: '6'
    tags: true
    repo: craft-ai/eslint-config-craft-ai
