language: node_js
node_js:
- '8'
- '6'
deploy:
  provider: npm
  email: ops@craft.ai
  api_key:
    secure: eZxeMooH40EmOyvZDVib6xyS11+TWB1oTVBfVtFscZkIS0w8GD6SAax+i/XHQpTZ1uPpRrlGy04vGk79t0xJP8nj4O0p9T6uZgfFhG28Y+E5rECOYlprEqq2O/qWgNJ8wMs10cPrqAoE4OPe1N7IW5+xmmmivFH8pK9tRdDFfBS3J/8XvNGhhzDQ1kT8Htki4lBMMFmFyS9P9hdKq0WbSnQSFWrD0wthyaqO/vorDCIBsYqCIlHpO6KWgrnBEoQPzXONNcfgJEy5PmqG9t1si1QIyjl+61aluTBPMC/ufvNit9Fggn87tLo5f3CHMkTcUBMfI5dDi6bgMDZyRQQXKvNCj9cAlYFzf0rG+t8lttLIyQbMFrV0Eh7/BtQF50/r8uju2U8Yn8rH+lPgi+eLisJSuNRIpKXRoUFJMabhxMYZHAmJsfrFyjxoTHZRjS0YzCj2eO8OEvBKD1amIl24DHyC5NNs/XQfpn5qL9n04KtKVdZXCFGOaqDtc8aRZxwk7R9Bhc+xtB1fiU6YW0LRrchZnRYeLl9EteyQaXCRea9/9E+EIX/IY3S/PHF30uRBpoWuTcdJ+k9cGHaN+OYkOkGZ4kaFLsWZNNsjFovLwJF/H/LMkaDVtFUiHUYfyc7i+yT3/3CynvrsdWGcJ1ubobgA0wSDFgOwN0bSxy5vjhI=
  on:
    node: '6'
    tags: true
    repo: craft-ai/eslint-config-craft-ai
